Phase 4 : Finalizing the migration (Switch each controller out of migration mode).
a) Stop the controller in the same way as the broker and update the controller configuration in the controller.properties file:
Remove the ZooKeeper connection details
Remove the zookeeper.metadata.migration.enable property
Remove inter.broker.listener.name
Restart the controller in the same way as the broker.
# ================================================================
# Phase 4 — KRaft Controller Final Configuration
# ZooKeeper completely removed from controller configuration
# This is the final production controller config
# ================================================================
# ──Controller Final Configuration───────────────────────────────────────

node.id=101
process.roles=controller

# ── KRaft Quorum ──────────────────────────────────────────────
controller.quorum.voters=101@broker1.example.com:9093,102@broker2.example.com:9093,103@broker3.example.com:9093
# ── Listener ──────────────────────────────────────────────────
controller.listener.names=CONTROLLER
listeners=CONTROLLER://broker1.example.com:9093
# ── Security ──────────────────────────────────────────────────
sasl.enabled.mechanisms=PLAIN
sasl.mechanism.controller.protocol=PLAIN
listener.security.protocol.map=CONTROLLER:SASL_PLAINTEXT
# ── Authorization ─────────────────────────────────────────────
authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
allow.everyone.if.no.acl.found=true
super.users=User:admin
# ── Storage ───────────────────────────────────────────────────
log.dirs=/opt/data/kraft/meta-logs



# ── REMOVED from Phase 2 ──────────────────────────────────────

# zookeeper.connect=...                         ← REMOVED

# zookeeper.metadata.migration.enable=true      ← REMOVED

# zookeeper.security.protocol=...               ← REMOVED

# inter.broker.listener.name=...                ← REMOVED

#######
NOTE - Once the migration has been finalized, you can safely deprovision your ZooKeeper cluster, 
assuming you are not using it for anything else. After this point, it is no longer possible to revert to ZooKeeper mode.

Phase 5 : Zookeeper Decommissioning

Shut down Zookeepers nodes.
Removed ZK configs from Kafka.
Confirmed clean operation in Kraft mode.
