# ================================================================

# Phase 1 — Preparation

# Enable TRACE logging for KRaft migration visibility

# Add these lines to existing log4j.properties on each broker

# and each KRaft controller node
STEP --1
# ================================================================
# Enable TRACE for migration driver

log4j.logger.org.apache.kafka.metadata.migration=TRACE

# Enable DEBUG for KRaft controller

log4j.logger.org.apache.kafka.controller=DEBUG

# Enable DEBUG for metadata

log4j.logger.org.apache.kafka.metadata=DEBUG


STEP 2)

Retrieve the cluster ID of your Kafka cluster- ./zookeeper-shell.sh ip-kfkzq01.com:2181 get /PT/QA/cluster/id

The command returns the cluster ID.
